# Generated by Django 4.1 on 2022-11-09 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_imagesend'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesend',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
