# Generated by Django 4.1 on 2023-02-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_imagesend_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageSend',
        ),
    ]
